### ISSUE TITLE
Dynamic Dolby Vision metadata not read correctly

### ISSUE THREAD

**Issue by damian101** [Lypheo/vs-placebo#40] opened 2023-05-22 01:27 UTC
With `use_dovi=True`, I get lots of random in-scene flickering due to single-frame tonemapping changes, random in-scene tonemapping changes, while there are no tonemapping changes where they should be, at the actual scene cuts. When playing the same source with mpv, the issue does not occur.

**Comment by damian101** [comment] 2023-05-22 01:58
I'm using lsmas.LWLibavSource. With ffms2.Source, dynamic Dolby Vision metadata can not be used at all.

**Comment by quietvoid** [comment] 2023-05-22 02:19
Please provide more info, such as an example script and clip where it happens.
I haven't seen stability issues on my side.

**Comment by damian101** [comment] 2023-05-22 13:01
> Please provide more info, such as an example script and clip where it happens. I haven't seen stability issues on my side.

Here is the relevant part of a script that is supposed to produce the equivalent from this (shortened) mpv script:
```
vo=gpu-next

target-prim=bt.709
gamut-mapping-mode=clip

[hdr]
profile-desc=HDR
profile-cond=p["video-params/gamma"] == "pq" or p["video-params/gamma"] == "hlg"
target-peak=200
tone-mapping=bt.2446a
tone-mapping-mode=luma
dolbyvision=yes
hdr-compute-peak=no
target-trc=bt.1886
tone-mapping-visualize
```
```
c = core.lsmas.LWLibavSource(source="sample.mkv")
c = core.std.CropAbs(clip=c, width=3840, height=2076, left=0, top=42)

c = core.resize.Bicubic(clip=c, format=vs.RGB48)
c = core.placebo.Tonemap(clip=c, src_csp=1, use_dovi=True, dynamic_peak_detection=0, dst_max=200, tone_mapping_function=3, tone_mapping_mode=4, gamut_mode=0, dst_csp=0, dst_prim=3, visualize_lut=True)
c = core.std.SetFrameProps(c, _Transfer=1, _Primaries=1)
```
But instead of the tonemapping changes happening invisibly at scenecuts, as in mpv, they happen between scenecuts, sometimes sporadically, causing flickering and incorrect tonemapping with often overblown highlights.

The issue happens on all sources for me, but I can provide a sample later.

Dynamic peak detection is broken for me too, btw, scene changes tend to happen too early for some reason, and the peak is sometimes heavily underestimated, causing severely overblown highlights. In mpv it works just fine.

**Comment by quietvoid** [comment] 2023-05-22 17:49
I can't reproduce any flickering when reencoding the sample with the script.
Nor with `use_dovi=True` or `dynamic_peak_detection=True`.

Sounds like your setup has something broken.

**Comment by damian101** [comment] 2023-06-05 18:02
Just had to rebuild everything to get it working again. But the issue still exists, just without the wild flickering so far. Dolby Vision tonemapping changes are not where they are supposed to be. In the sample I sent, I get the Dolby Vision tonemapping change for minute ~00:39 at ~00:36 already, ~3 seconds too early. In mpv, that tonemapping change occurs precisely on the scene change. So dynamic Dolby Vision metadata is definitely broken in vs-placebo, for me anyway.

**Comment by quietvoid** [comment] 2023-06-05 18:14
What happens when you tone map profile 5 Dolby Vision to PQ?
With `src_csp=3, dst_csp=1` and the samples here: https://developer.dolby.com/tools-media/sample-media/video-streams/dolby-vision-streams/

There's no issue on my side regarding the Dolby Vision metadata, it's working as expected.

**Comment by damian101** [comment] 2023-06-12 10:04
> What happens when you tone map profile 5 Dolby Vision to PQ? With `src_csp=3, dst_csp=1` and the samples here: https://developer.dolby.com/tools-media/sample-media/video-streams/dolby-vision-streams/
> 
> There's no issue on my side regarding the Dolby Vision metadata, it's working as expected.

Same issue, as expected. The dynamic metadata gets mapped to the wrong frames, scenecuts are not all where they are supposed to be. Interestingly, I get a different output everytime, the error is not deterministic.

Are you sure it's working for you? Did you check with visualize_lut=True that all tonemapping changes coincide with actual cuts?

**Comment by quietvoid** [comment] 2023-06-12 11:28
Of course I'm sure it's working for me. It's been working ever since Dolby Vision is supported.
If the changes are not deterministic the only thing I can think of is that something is messing with your frame or even props order.

You're seemingly the only one reporting such issues so to me it looks a lot like a problem on your side and not in `vs-placebo`.
I'm gonna close this.

**Closed by quietvoid** 2023-06-12 11:28 UTC

**Comment by damian101** [comment] 2023-06-12 16:15
I just tried the same VapourSynth script on my new laptop, also Arch Linux, and using the Nvidia GPU everything works fine. Can't use the Intel iGPU because the driver is broken, Alder Lake...
The GPU in my other system is an AMD Radeon RX 480... Tried both vulkan-radeon and amdvlk, both produce the issue.

**Comment by damian101** [comment] 2023-08-14 13:33
I have a Linux installation on a USB drive. When I put it in my laptop, Dolby Vision metadata is read correctly with vs-placebo, on both the Intel and the Nvidia GPU. But when I put the drive in the same system I have this issue on, and boot into it, this issue appears again. In that system, the GPU is a Radeon RX 580. Using different AMD Radeon Vulkan drivers does not fix the issue.
